/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * GENERATED by generate_catalog.js from MITRE ATT&CK v19.1 — do not hand-edit.
 *
 * MITRE ATT&CK® is a registered trademark of The MITRE Corporation. © 2026
 * The MITRE Corporation. This work is reproduced and distributed with the permission of The
 * MITRE Corporation. See NOTICE.txt for the full attribution.
 */

import { AttackCatalog } from './catalog';

export const ATTACK_CATALOG: AttackCatalog = {
  version: '19.1',
  tactics: [
    {
      id: 'TA0001',
      name: 'Initial Access',
      shortname: 'initial-access',
    },
    {
      id: 'TA0002',
      name: 'Execution',
      shortname: 'execution',
    },
    {
      id: 'TA0003',
      name: 'Persistence',
      shortname: 'persistence',
    },
    {
      id: 'TA0004',
      name: 'Privilege Escalation',
      shortname: 'privilege-escalation',
    },
    {
      id: 'TA0005',
      name: 'Stealth',
      shortname: 'stealth',
    },
    {
      id: 'TA0006',
      name: 'Credential Access',
      shortname: 'credential-access',
    },
    {
      id: 'TA0007',
      name: 'Discovery',
      shortname: 'discovery',
    },
    {
      id: 'TA0008',
      name: 'Lateral Movement',
      shortname: 'lateral-movement',
    },
    {
      id: 'TA0009',
      name: 'Collection',
      shortname: 'collection',
    },
    {
      id: 'TA0010',
      name: 'Exfiltration',
      shortname: 'exfiltration',
    },
    {
      id: 'TA0011',
      name: 'Command and Control',
      shortname: 'command-and-control',
    },
    {
      id: 'TA0040',
      name: 'Impact',
      shortname: 'impact',
    },
    {
      id: 'TA0042',
      name: 'Resource Development',
      shortname: 'resource-development',
    },
    {
      id: 'TA0043',
      name: 'Reconnaissance',
      shortname: 'reconnaissance',
    },
    {
      id: 'TA0112',
      name: 'Defense Impairment',
      shortname: 'defense-impairment',
    },
  ],
  techniques: [
    {
      id: 'T1001',
      name: 'Data Obfuscation',
      tactics: ['command-and-control'],
      sub: [
        {
          id: 'T1001.001',
          name: 'Junk Data',
        },
        {
          id: 'T1001.002',
          name: 'Steganography',
        },
        {
          id: 'T1001.003',
          name: 'Protocol or Service Impersonation',
        },
      ],
    },
    {
      id: 'T1003',
      name: 'OS Credential Dumping',
      tactics: ['credential-access'],
      sub: [
        {
          id: 'T1003.001',
          name: 'LSASS Memory',
        },
        {
          id: 'T1003.002',
          name: 'Security Account Manager',
        },
        {
          id: 'T1003.003',
          name: 'NTDS',
        },
        {
          id: 'T1003.004',
          name: 'LSA Secrets',
        },
        {
          id: 'T1003.005',
          name: 'Cached Domain Credentials',
        },
        {
          id: 'T1003.006',
          name: 'DCSync',
        },
        {
          id: 'T1003.007',
          name: 'Proc Filesystem',
        },
        {
          id: 'T1003.008',
          name: '/etc/passwd and /etc/shadow',
        },
      ],
    },
    {
      id: 'T1005',
      name: 'Data from Local System',
      tactics: ['collection'],
      sub: [],
    },
    {
      id: 'T1006',
      name: 'Direct Volume Access',
      tactics: ['stealth'],
      sub: [],
    },
    {
      id: 'T1007',
      name: 'System Service Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1008',
      name: 'Fallback Channels',
      tactics: ['command-and-control'],
      sub: [],
    },
    {
      id: 'T1010',
      name: 'Application Window Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1011',
      name: 'Exfiltration Over Other Network Medium',
      tactics: ['exfiltration'],
      sub: [
        {
          id: 'T1011.001',
          name: 'Exfiltration Over Bluetooth',
        },
      ],
    },
    {
      id: 'T1012',
      name: 'Query Registry',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1014',
      name: 'Rootkit',
      tactics: ['stealth'],
      sub: [],
    },
    {
      id: 'T1016',
      name: 'System Network Configuration Discovery',
      tactics: ['discovery'],
      sub: [
        {
          id: 'T1016.001',
          name: 'Internet Connection Discovery',
        },
        {
          id: 'T1016.002',
          name: 'Wi-Fi Discovery',
        },
      ],
    },
    {
      id: 'T1018',
      name: 'Remote System Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1020',
      name: 'Automated Exfiltration',
      tactics: ['exfiltration'],
      sub: [
        {
          id: 'T1020.001',
          name: 'Traffic Duplication',
        },
      ],
    },
    {
      id: 'T1021',
      name: 'Remote Services',
      tactics: ['lateral-movement'],
      sub: [
        {
          id: 'T1021.001',
          name: 'Remote Desktop Protocol',
        },
        {
          id: 'T1021.002',
          name: 'SMB/Windows Admin Shares',
        },
        {
          id: 'T1021.003',
          name: 'Distributed Component Object Model',
        },
        {
          id: 'T1021.004',
          name: 'SSH',
        },
        {
          id: 'T1021.005',
          name: 'VNC',
        },
        {
          id: 'T1021.006',
          name: 'Windows Remote Management',
        },
        {
          id: 'T1021.007',
          name: 'Cloud Services',
        },
        {
          id: 'T1021.008',
          name: 'Direct Cloud VM Connections',
        },
      ],
    },
    {
      id: 'T1025',
      name: 'Data from Removable Media',
      tactics: ['collection'],
      sub: [],
    },
    {
      id: 'T1027',
      name: 'Obfuscated Files or Information',
      tactics: ['stealth'],
      sub: [
        {
          id: 'T1027.001',
          name: 'Binary Padding',
        },
        {
          id: 'T1027.002',
          name: 'Software Packing',
        },
        {
          id: 'T1027.003',
          name: 'Steganography',
        },
        {
          id: 'T1027.004',
          name: 'Compile After Delivery',
        },
        {
          id: 'T1027.005',
          name: 'Indicator Removal from Tools',
        },
        {
          id: 'T1027.006',
          name: 'HTML Smuggling',
        },
        {
          id: 'T1027.007',
          name: 'Dynamic API Resolution',
        },
        {
          id: 'T1027.008',
          name: 'Stripped Payloads',
        },
        {
          id: 'T1027.009',
          name: 'Embedded Payloads',
        },
        {
          id: 'T1027.010',
          name: 'Command Obfuscation',
        },
        {
          id: 'T1027.011',
          name: 'Fileless Storage',
        },
        {
          id: 'T1027.012',
          name: 'LNK Icon Smuggling',
        },
        {
          id: 'T1027.013',
          name: 'Encrypted/Encoded File',
        },
        {
          id: 'T1027.014',
          name: 'Polymorphic Code',
        },
        {
          id: 'T1027.015',
          name: 'Compression',
        },
        {
          id: 'T1027.016',
          name: 'Junk Code Insertion',
        },
        {
          id: 'T1027.017',
          name: 'SVG Smuggling',
        },
        {
          id: 'T1027.018',
          name: 'Invisible Unicode',
        },
      ],
    },
    {
      id: 'T1029',
      name: 'Scheduled Transfer',
      tactics: ['exfiltration'],
      sub: [],
    },
    {
      id: 'T1030',
      name: 'Data Transfer Size Limits',
      tactics: ['exfiltration'],
      sub: [],
    },
    {
      id: 'T1033',
      name: 'System Owner/User Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1036',
      name: 'Masquerading',
      tactics: ['stealth'],
      sub: [
        {
          id: 'T1036.001',
          name: 'Invalid Code Signature',
        },
        {
          id: 'T1036.002',
          name: 'Right-to-Left Override',
        },
        {
          id: 'T1036.003',
          name: 'Rename Legitimate Utilities',
        },
        {
          id: 'T1036.004',
          name: 'Masquerade Task or Service',
        },
        {
          id: 'T1036.005',
          name: 'Match Legitimate Resource Name or Location',
        },
        {
          id: 'T1036.006',
          name: 'Space after Filename',
        },
        {
          id: 'T1036.007',
          name: 'Double File Extension',
        },
        {
          id: 'T1036.008',
          name: 'Masquerade File Type',
        },
        {
          id: 'T1036.009',
          name: 'Break Process Trees',
        },
        {
          id: 'T1036.010',
          name: 'Masquerade Account Name',
        },
        {
          id: 'T1036.011',
          name: 'Overwrite Process Arguments',
        },
        {
          id: 'T1036.012',
          name: 'Browser Fingerprint',
        },
      ],
    },
    {
      id: 'T1037',
      name: 'Boot or Logon Initialization Scripts',
      tactics: ['persistence', 'privilege-escalation'],
      sub: [
        {
          id: 'T1037.001',
          name: 'Logon Script (Windows)',
        },
        {
          id: 'T1037.002',
          name: 'Login Hook',
        },
        {
          id: 'T1037.003',
          name: 'Network Logon Script',
        },
        {
          id: 'T1037.004',
          name: 'RC Scripts',
        },
        {
          id: 'T1037.005',
          name: 'Startup Items',
        },
      ],
    },
    {
      id: 'T1039',
      name: 'Data from Network Shared Drive',
      tactics: ['collection'],
      sub: [],
    },
    {
      id: 'T1040',
      name: 'Network Sniffing',
      tactics: ['credential-access', 'discovery'],
      sub: [],
    },
    {
      id: 'T1041',
      name: 'Exfiltration Over C2 Channel',
      tactics: ['exfiltration'],
      sub: [],
    },
    {
      id: 'T1046',
      name: 'Network Service Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1047',
      name: 'Windows Management Instrumentation',
      tactics: ['execution'],
      sub: [],
    },
    {
      id: 'T1048',
      name: 'Exfiltration Over Alternative Protocol',
      tactics: ['exfiltration'],
      sub: [
        {
          id: 'T1048.001',
          name: 'Exfiltration Over Symmetric Encrypted Non-C2 Protocol',
        },
        {
          id: 'T1048.002',
          name: 'Exfiltration Over Asymmetric Encrypted Non-C2 Protocol',
        },
        {
          id: 'T1048.003',
          name: 'Exfiltration Over Unencrypted Non-C2 Protocol',
        },
      ],
    },
    {
      id: 'T1049',
      name: 'System Network Connections Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1052',
      name: 'Exfiltration Over Physical Medium',
      tactics: ['exfiltration'],
      sub: [
        {
          id: 'T1052.001',
          name: 'Exfiltration over USB',
        },
      ],
    },
    {
      id: 'T1053',
      name: 'Scheduled Task/Job',
      tactics: ['execution', 'persistence', 'privilege-escalation'],
      sub: [
        {
          id: 'T1053.002',
          name: 'At',
        },
        {
          id: 'T1053.003',
          name: 'Cron',
        },
        {
          id: 'T1053.005',
          name: 'Scheduled Task',
        },
        {
          id: 'T1053.006',
          name: 'Systemd Timers',
        },
        {
          id: 'T1053.007',
          name: 'Container Orchestration Job',
        },
      ],
    },
    {
      id: 'T1055',
      name: 'Process Injection',
      tactics: ['stealth', 'privilege-escalation'],
      sub: [
        {
          id: 'T1055.001',
          name: 'Dynamic-link Library Injection',
        },
        {
          id: 'T1055.002',
          name: 'Portable Executable Injection',
        },
        {
          id: 'T1055.003',
          name: 'Thread Execution Hijacking',
        },
        {
          id: 'T1055.004',
          name: 'Asynchronous Procedure Call',
        },
        {
          id: 'T1055.005',
          name: 'Thread Local Storage',
        },
        {
          id: 'T1055.008',
          name: 'Ptrace System Calls',
        },
        {
          id: 'T1055.009',
          name: 'Proc Memory',
        },
        {
          id: 'T1055.011',
          name: 'Extra Window Memory Injection',
        },
        {
          id: 'T1055.012',
          name: 'Process Hollowing',
        },
        {
          id: 'T1055.013',
          name: 'Process Doppelgänging',
        },
        {
          id: 'T1055.014',
          name: 'VDSO Hijacking',
        },
        {
          id: 'T1055.015',
          name: 'ListPlanting',
        },
      ],
    },
    {
      id: 'T1056',
      name: 'Input Capture',
      tactics: ['collection', 'credential-access'],
      sub: [
        {
          id: 'T1056.001',
          name: 'Keylogging',
        },
        {
          id: 'T1056.002',
          name: 'GUI Input Capture',
        },
        {
          id: 'T1056.003',
          name: 'Web Portal Capture',
        },
        {
          id: 'T1056.004',
          name: 'Credential API Hooking',
        },
      ],
    },
    {
      id: 'T1057',
      name: 'Process Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1059',
      name: 'Command and Scripting Interpreter',
      tactics: ['execution'],
      sub: [
        {
          id: 'T1059.001',
          name: 'PowerShell',
        },
        {
          id: 'T1059.002',
          name: 'AppleScript',
        },
        {
          id: 'T1059.003',
          name: 'Windows Command Shell',
        },
        {
          id: 'T1059.004',
          name: 'Unix Shell',
        },
        {
          id: 'T1059.005',
          name: 'Visual Basic',
        },
        {
          id: 'T1059.006',
          name: 'Python',
        },
        {
          id: 'T1059.007',
          name: 'JavaScript',
        },
        {
          id: 'T1059.008',
          name: 'Network Device CLI',
        },
        {
          id: 'T1059.009',
          name: 'Cloud API',
        },
        {
          id: 'T1059.010',
          name: 'AutoHotKey & AutoIT',
        },
        {
          id: 'T1059.011',
          name: 'Lua',
        },
        {
          id: 'T1059.012',
          name: 'Hypervisor CLI',
        },
        {
          id: 'T1059.013',
          name: 'Container CLI/API',
        },
      ],
    },
    {
      id: 'T1068',
      name: 'Exploitation for Privilege Escalation',
      tactics: ['privilege-escalation'],
      sub: [],
    },
    {
      id: 'T1069',
      name: 'Permission Groups Discovery',
      tactics: ['discovery'],
      sub: [
        {
          id: 'T1069.001',
          name: 'Local Groups',
        },
        {
          id: 'T1069.002',
          name: 'Domain Groups',
        },
        {
          id: 'T1069.003',
          name: 'Cloud Groups',
        },
      ],
    },
    {
      id: 'T1070',
      name: 'Indicator Removal',
      tactics: ['stealth'],
      sub: [
        {
          id: 'T1070.003',
          name: 'Clear Command History',
        },
        {
          id: 'T1070.004',
          name: 'File Deletion',
        },
        {
          id: 'T1070.005',
          name: 'Network Share Connection Removal',
        },
        {
          id: 'T1070.006',
          name: 'Timestomp',
        },
        {
          id: 'T1070.007',
          name: 'Clear Network Connection History and Configurations',
        },
        {
          id: 'T1070.008',
          name: 'Clear Mailbox Data',
        },
        {
          id: 'T1070.009',
          name: 'Clear Persistence',
        },
        {
          id: 'T1070.010',
          name: 'Relocate Malware',
        },
      ],
    },
    {
      id: 'T1071',
      name: 'Application Layer Protocol',
      tactics: ['command-and-control'],
      sub: [
        {
          id: 'T1071.001',
          name: 'Web Protocols',
        },
        {
          id: 'T1071.002',
          name: 'File Transfer Protocols',
        },
        {
          id: 'T1071.003',
          name: 'Mail Protocols',
        },
        {
          id: 'T1071.004',
          name: 'DNS',
        },
        {
          id: 'T1071.005',
          name: 'Publish/Subscribe Protocols',
        },
      ],
    },
    {
      id: 'T1072',
      name: 'Software Deployment Tools',
      tactics: ['execution', 'lateral-movement'],
      sub: [],
    },
    {
      id: 'T1074',
      name: 'Data Staged',
      tactics: ['collection'],
      sub: [
        {
          id: 'T1074.001',
          name: 'Local Data Staging',
        },
        {
          id: 'T1074.002',
          name: 'Remote Data Staging',
        },
      ],
    },
    {
      id: 'T1078',
      name: 'Valid Accounts',
      tactics: ['stealth', 'persistence', 'privilege-escalation', 'initial-access'],
      sub: [
        {
          id: 'T1078.001',
          name: 'Default Accounts',
        },
        {
          id: 'T1078.002',
          name: 'Domain Accounts',
        },
        {
          id: 'T1078.003',
          name: 'Local Accounts',
        },
        {
          id: 'T1078.004',
          name: 'Cloud Accounts',
        },
      ],
    },
    {
      id: 'T1080',
      name: 'Taint Shared Content',
      tactics: ['lateral-movement'],
      sub: [],
    },
    {
      id: 'T1082',
      name: 'System Information Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1083',
      name: 'File and Directory Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1087',
      name: 'Account Discovery',
      tactics: ['discovery'],
      sub: [
        {
          id: 'T1087.001',
          name: 'Local Account',
        },
        {
          id: 'T1087.002',
          name: 'Domain Account',
        },
        {
          id: 'T1087.003',
          name: 'Email Account',
        },
        {
          id: 'T1087.004',
          name: 'Cloud Account',
        },
      ],
    },
    {
      id: 'T1090',
      name: 'Proxy',
      tactics: ['command-and-control'],
      sub: [
        {
          id: 'T1090.001',
          name: 'Internal Proxy',
        },
        {
          id: 'T1090.002',
          name: 'External Proxy',
        },
        {
          id: 'T1090.003',
          name: 'Multi-hop Proxy',
        },
        {
          id: 'T1090.004',
          name: 'Domain Fronting',
        },
      ],
    },
    {
      id: 'T1091',
      name: 'Replication Through Removable Media',
      tactics: ['lateral-movement', 'initial-access'],
      sub: [],
    },
    {
      id: 'T1092',
      name: 'Communication Through Removable Media',
      tactics: ['command-and-control'],
      sub: [],
    },
    {
      id: 'T1095',
      name: 'Non-Application Layer Protocol',
      tactics: ['command-and-control'],
      sub: [],
    },
    {
      id: 'T1098',
      name: 'Account Manipulation',
      tactics: ['persistence', 'privilege-escalation'],
      sub: [
        {
          id: 'T1098.001',
          name: 'Additional Cloud Credentials',
        },
        {
          id: 'T1098.002',
          name: 'Additional Email Delegate Permissions',
        },
        {
          id: 'T1098.003',
          name: 'Additional Cloud Roles',
        },
        {
          id: 'T1098.004',
          name: 'SSH Authorized Keys',
        },
        {
          id: 'T1098.005',
          name: 'Device Registration',
        },
        {
          id: 'T1098.006',
          name: 'Additional Container Cluster Roles',
        },
        {
          id: 'T1098.007',
          name: 'Additional Local or Domain Groups',
        },
      ],
    },
    {
      id: 'T1102',
      name: 'Web Service',
      tactics: ['command-and-control'],
      sub: [
        {
          id: 'T1102.001',
          name: 'Dead Drop Resolver',
        },
        {
          id: 'T1102.002',
          name: 'Bidirectional Communication',
        },
        {
          id: 'T1102.003',
          name: 'One-Way Communication',
        },
      ],
    },
    {
      id: 'T1104',
      name: 'Multi-Stage Channels',
      tactics: ['command-and-control'],
      sub: [],
    },
    {
      id: 'T1105',
      name: 'Ingress Tool Transfer',
      tactics: ['command-and-control'],
      sub: [],
    },
    {
      id: 'T1106',
      name: 'Native API',
      tactics: ['execution'],
      sub: [],
    },
    {
      id: 'T1110',
      name: 'Brute Force',
      tactics: ['credential-access'],
      sub: [
        {
          id: 'T1110.001',
          name: 'Password Guessing',
        },
        {
          id: 'T1110.002',
          name: 'Password Cracking',
        },
        {
          id: 'T1110.003',
          name: 'Password Spraying',
        },
        {
          id: 'T1110.004',
          name: 'Credential Stuffing',
        },
      ],
    },
    {
      id: 'T1111',
      name: 'Multi-Factor Authentication Interception',
      tactics: ['credential-access'],
      sub: [],
    },
    {
      id: 'T1112',
      name: 'Modify Registry',
      tactics: ['defense-impairment', 'persistence'],
      sub: [],
    },
    {
      id: 'T1113',
      name: 'Screen Capture',
      tactics: ['collection'],
      sub: [],
    },
    {
      id: 'T1114',
      name: 'Email Collection',
      tactics: ['collection'],
      sub: [
        {
          id: 'T1114.001',
          name: 'Local Email Collection',
        },
        {
          id: 'T1114.002',
          name: 'Remote Email Collection',
        },
        {
          id: 'T1114.003',
          name: 'Email Forwarding Rule',
        },
      ],
    },
    {
      id: 'T1115',
      name: 'Clipboard Data',
      tactics: ['collection'],
      sub: [],
    },
    {
      id: 'T1119',
      name: 'Automated Collection',
      tactics: ['collection'],
      sub: [],
    },
    {
      id: 'T1120',
      name: 'Peripheral Device Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1123',
      name: 'Audio Capture',
      tactics: ['collection'],
      sub: [],
    },
    {
      id: 'T1124',
      name: 'System Time Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1125',
      name: 'Video Capture',
      tactics: ['collection'],
      sub: [],
    },
    {
      id: 'T1127',
      name: 'Trusted Developer Utilities Proxy Execution',
      tactics: ['stealth', 'execution'],
      sub: [
        {
          id: 'T1127.001',
          name: 'MSBuild',
        },
        {
          id: 'T1127.002',
          name: 'ClickOnce',
        },
        {
          id: 'T1127.003',
          name: 'JamPlus',
        },
      ],
    },
    {
      id: 'T1129',
      name: 'Shared Modules',
      tactics: ['execution'],
      sub: [],
    },
    {
      id: 'T1132',
      name: 'Data Encoding',
      tactics: ['command-and-control'],
      sub: [
        {
          id: 'T1132.001',
          name: 'Standard Encoding',
        },
        {
          id: 'T1132.002',
          name: 'Non-Standard Encoding',
        },
      ],
    },
    {
      id: 'T1133',
      name: 'External Remote Services',
      tactics: ['persistence', 'initial-access'],
      sub: [],
    },
    {
      id: 'T1134',
      name: 'Access Token Manipulation',
      tactics: ['stealth', 'privilege-escalation'],
      sub: [
        {
          id: 'T1134.001',
          name: 'Token Impersonation/Theft',
        },
        {
          id: 'T1134.002',
          name: 'Create Process with Token',
        },
        {
          id: 'T1134.003',
          name: 'Make and Impersonate Token',
        },
        {
          id: 'T1134.004',
          name: 'Parent PID Spoofing',
        },
        {
          id: 'T1134.005',
          name: 'SID-History Injection',
        },
      ],
    },
    {
      id: 'T1135',
      name: 'Network Share Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1136',
      name: 'Create Account',
      tactics: ['persistence'],
      sub: [
        {
          id: 'T1136.001',
          name: 'Local Account',
        },
        {
          id: 'T1136.002',
          name: 'Domain Account',
        },
        {
          id: 'T1136.003',
          name: 'Cloud Account',
        },
      ],
    },
    {
      id: 'T1137',
      name: 'Office Application Startup',
      tactics: ['persistence'],
      sub: [
        {
          id: 'T1137.001',
          name: 'Office Template Macros',
        },
        {
          id: 'T1137.002',
          name: 'Office Test',
        },
        {
          id: 'T1137.003',
          name: 'Outlook Forms',
        },
        {
          id: 'T1137.004',
          name: 'Outlook Home Page',
        },
        {
          id: 'T1137.005',
          name: 'Outlook Rules',
        },
        {
          id: 'T1137.006',
          name: 'Add-ins',
        },
      ],
    },
    {
      id: 'T1140',
      name: 'Deobfuscate/Decode Files or Information',
      tactics: ['stealth'],
      sub: [],
    },
    {
      id: 'T1176',
      name: 'Software Extensions',
      tactics: ['persistence'],
      sub: [
        {
          id: 'T1176.001',
          name: 'Browser Extensions',
        },
        {
          id: 'T1176.002',
          name: 'IDE Extensions',
        },
      ],
    },
    {
      id: 'T1185',
      name: 'Browser Session Hijacking',
      tactics: ['collection'],
      sub: [],
    },
    {
      id: 'T1187',
      name: 'Forced Authentication',
      tactics: ['credential-access'],
      sub: [],
    },
    {
      id: 'T1189',
      name: 'Drive-by Compromise',
      tactics: ['initial-access'],
      sub: [],
    },
    {
      id: 'T1190',
      name: 'Exploit Public-Facing Application',
      tactics: ['initial-access'],
      sub: [],
    },
    {
      id: 'T1195',
      name: 'Supply Chain Compromise',
      tactics: ['initial-access'],
      sub: [
        {
          id: 'T1195.001',
          name: 'Compromise Software Dependencies and Development Tools',
        },
        {
          id: 'T1195.002',
          name: 'Compromise Software Supply Chain',
        },
        {
          id: 'T1195.003',
          name: 'Compromise Hardware Supply Chain',
        },
      ],
    },
    {
      id: 'T1197',
      name: 'BITS Jobs',
      tactics: ['stealth', 'persistence', 'execution'],
      sub: [],
    },
    {
      id: 'T1199',
      name: 'Trusted Relationship',
      tactics: ['initial-access'],
      sub: [],
    },
    {
      id: 'T1200',
      name: 'Hardware Additions',
      tactics: ['initial-access'],
      sub: [],
    },
    {
      id: 'T1201',
      name: 'Password Policy Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1202',
      name: 'Indirect Command Execution',
      tactics: ['stealth'],
      sub: [],
    },
    {
      id: 'T1203',
      name: 'Exploitation for Client Execution',
      tactics: ['execution'],
      sub: [],
    },
    {
      id: 'T1204',
      name: 'User Execution',
      tactics: ['execution'],
      sub: [
        {
          id: 'T1204.001',
          name: 'Malicious Link',
        },
        {
          id: 'T1204.002',
          name: 'Malicious File',
        },
        {
          id: 'T1204.003',
          name: 'Malicious Image',
        },
        {
          id: 'T1204.004',
          name: 'Malicious Copy and Paste',
        },
        {
          id: 'T1204.005',
          name: 'Malicious Library',
        },
      ],
    },
    {
      id: 'T1205',
      name: 'Traffic Signaling',
      tactics: ['stealth', 'persistence', 'command-and-control'],
      sub: [
        {
          id: 'T1205.001',
          name: 'Port Knocking',
        },
        {
          id: 'T1205.002',
          name: 'Socket Filters',
        },
      ],
    },
    {
      id: 'T1207',
      name: 'Rogue Domain Controller',
      tactics: ['defense-impairment'],
      sub: [],
    },
    {
      id: 'T1210',
      name: 'Exploitation of Remote Services',
      tactics: ['lateral-movement'],
      sub: [],
    },
    {
      id: 'T1211',
      name: 'Exploitation for Stealth',
      tactics: ['stealth'],
      sub: [],
    },
    {
      id: 'T1212',
      name: 'Exploitation for Credential Access',
      tactics: ['credential-access'],
      sub: [],
    },
    {
      id: 'T1213',
      name: 'Data from Information Repositories',
      tactics: ['collection'],
      sub: [
        {
          id: 'T1213.001',
          name: 'Confluence',
        },
        {
          id: 'T1213.002',
          name: 'Sharepoint',
        },
        {
          id: 'T1213.003',
          name: 'Code Repositories',
        },
        {
          id: 'T1213.004',
          name: 'Customer Relationship Management Software',
        },
        {
          id: 'T1213.005',
          name: 'Messaging Applications',
        },
        {
          id: 'T1213.006',
          name: 'Databases',
        },
      ],
    },
    {
      id: 'T1216',
      name: 'System Script Proxy Execution',
      tactics: ['stealth'],
      sub: [
        {
          id: 'T1216.001',
          name: 'PubPrn',
        },
        {
          id: 'T1216.002',
          name: 'SyncAppvPublishingServer',
        },
      ],
    },
    {
      id: 'T1217',
      name: 'Browser Information Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1218',
      name: 'System Binary Proxy Execution',
      tactics: ['stealth'],
      sub: [
        {
          id: 'T1218.001',
          name: 'Compiled HTML File',
        },
        {
          id: 'T1218.002',
          name: 'Control Panel',
        },
        {
          id: 'T1218.003',
          name: 'CMSTP',
        },
        {
          id: 'T1218.004',
          name: 'InstallUtil',
        },
        {
          id: 'T1218.005',
          name: 'Mshta',
        },
        {
          id: 'T1218.007',
          name: 'Msiexec',
        },
        {
          id: 'T1218.008',
          name: 'Odbcconf',
        },
        {
          id: 'T1218.009',
          name: 'Regsvcs/Regasm',
        },
        {
          id: 'T1218.010',
          name: 'Regsvr32',
        },
        {
          id: 'T1218.011',
          name: 'Rundll32',
        },
        {
          id: 'T1218.012',
          name: 'Verclsid',
        },
        {
          id: 'T1218.013',
          name: 'Mavinject',
        },
        {
          id: 'T1218.014',
          name: 'MMC',
        },
        {
          id: 'T1218.015',
          name: 'Electron Applications',
        },
      ],
    },
    {
      id: 'T1219',
      name: 'Remote Access Tools',
      tactics: ['command-and-control'],
      sub: [
        {
          id: 'T1219.001',
          name: 'IDE Tunneling',
        },
        {
          id: 'T1219.002',
          name: 'Remote Desktop Software',
        },
        {
          id: 'T1219.003',
          name: 'Remote Access Hardware',
        },
      ],
    },
    {
      id: 'T1220',
      name: 'XSL Script Processing',
      tactics: ['stealth'],
      sub: [],
    },
    {
      id: 'T1221',
      name: 'Template Injection',
      tactics: ['stealth'],
      sub: [],
    },
    {
      id: 'T1222',
      name: 'File and Directory Permissions Modification',
      tactics: ['defense-impairment'],
      sub: [
        {
          id: 'T1222.001',
          name: 'Windows Permissions',
        },
        {
          id: 'T1222.002',
          name: 'Linux and Mac Permissions',
        },
      ],
    },
    {
      id: 'T1480',
      name: 'Execution Guardrails',
      tactics: ['stealth'],
      sub: [
        {
          id: 'T1480.001',
          name: 'Environmental Keying',
        },
        {
          id: 'T1480.002',
          name: 'Mutual Exclusion',
        },
      ],
    },
    {
      id: 'T1482',
      name: 'Domain Trust Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1484',
      name: 'Domain or Tenant Policy Modification',
      tactics: ['defense-impairment', 'privilege-escalation'],
      sub: [
        {
          id: 'T1484.001',
          name: 'Group Policy Modification',
        },
        {
          id: 'T1484.002',
          name: 'Trust Modification',
        },
      ],
    },
    {
      id: 'T1485',
      name: 'Data Destruction',
      tactics: ['impact'],
      sub: [
        {
          id: 'T1485.001',
          name: 'Lifecycle-Triggered Deletion',
        },
      ],
    },
    {
      id: 'T1486',
      name: 'Data Encrypted for Impact',
      tactics: ['impact'],
      sub: [],
    },
    {
      id: 'T1489',
      name: 'Service Stop',
      tactics: ['impact'],
      sub: [],
    },
    {
      id: 'T1490',
      name: 'Inhibit System Recovery',
      tactics: ['impact'],
      sub: [],
    },
    {
      id: 'T1491',
      name: 'Defacement',
      tactics: ['impact'],
      sub: [
        {
          id: 'T1491.001',
          name: 'Internal Defacement',
        },
        {
          id: 'T1491.002',
          name: 'External Defacement',
        },
      ],
    },
    {
      id: 'T1495',
      name: 'Firmware Corruption',
      tactics: ['impact'],
      sub: [],
    },
    {
      id: 'T1496',
      name: 'Resource Hijacking',
      tactics: ['impact'],
      sub: [
        {
          id: 'T1496.001',
          name: 'Compute Hijacking',
        },
        {
          id: 'T1496.002',
          name: 'Bandwidth Hijacking',
        },
        {
          id: 'T1496.003',
          name: 'SMS Pumping',
        },
        {
          id: 'T1496.004',
          name: 'Cloud Service Hijacking',
        },
      ],
    },
    {
      id: 'T1497',
      name: 'Virtualization/Sandbox Evasion',
      tactics: ['stealth', 'discovery'],
      sub: [
        {
          id: 'T1497.001',
          name: 'System Checks',
        },
        {
          id: 'T1497.002',
          name: 'User Activity Based Checks',
        },
        {
          id: 'T1497.003',
          name: 'Time Based Checks',
        },
      ],
    },
    {
      id: 'T1498',
      name: 'Network Denial of Service',
      tactics: ['impact'],
      sub: [
        {
          id: 'T1498.001',
          name: 'Direct Network Flood',
        },
        {
          id: 'T1498.002',
          name: 'Reflection Amplification',
        },
      ],
    },
    {
      id: 'T1499',
      name: 'Endpoint Denial of Service',
      tactics: ['impact'],
      sub: [
        {
          id: 'T1499.001',
          name: 'OS Exhaustion Flood',
        },
        {
          id: 'T1499.002',
          name: 'Service Exhaustion Flood',
        },
        {
          id: 'T1499.003',
          name: 'Application Exhaustion Flood',
        },
        {
          id: 'T1499.004',
          name: 'Application or System Exploitation',
        },
      ],
    },
    {
      id: 'T1505',
      name: 'Server Software Component',
      tactics: ['persistence'],
      sub: [
        {
          id: 'T1505.001',
          name: 'SQL Stored Procedures',
        },
        {
          id: 'T1505.002',
          name: 'Transport Agent',
        },
        {
          id: 'T1505.003',
          name: 'Web Shell',
        },
        {
          id: 'T1505.004',
          name: 'IIS Components',
        },
        {
          id: 'T1505.005',
          name: 'Terminal Services DLL',
        },
        {
          id: 'T1505.006',
          name: 'vSphere Installation Bundles',
        },
      ],
    },
    {
      id: 'T1518',
      name: 'Software Discovery',
      tactics: ['discovery'],
      sub: [
        {
          id: 'T1518.001',
          name: 'Security Software Discovery',
        },
        {
          id: 'T1518.002',
          name: 'Backup Software Discovery',
        },
      ],
    },
    {
      id: 'T1525',
      name: 'Implant Internal Image',
      tactics: ['persistence'],
      sub: [],
    },
    {
      id: 'T1526',
      name: 'Cloud Service Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1528',
      name: 'Steal Application Access Token',
      tactics: ['credential-access'],
      sub: [],
    },
    {
      id: 'T1529',
      name: 'System Shutdown/Reboot',
      tactics: ['impact'],
      sub: [],
    },
    {
      id: 'T1530',
      name: 'Data from Cloud Storage',
      tactics: ['collection'],
      sub: [],
    },
    {
      id: 'T1531',
      name: 'Account Access Removal',
      tactics: ['impact'],
      sub: [],
    },
    {
      id: 'T1534',
      name: 'Internal Spearphishing',
      tactics: ['lateral-movement'],
      sub: [],
    },
    {
      id: 'T1535',
      name: 'Unused/Unsupported Cloud Regions',
      tactics: ['stealth'],
      sub: [],
    },
    {
      id: 'T1537',
      name: 'Transfer Data to Cloud Account',
      tactics: ['exfiltration'],
      sub: [],
    },
    {
      id: 'T1538',
      name: 'Cloud Service Dashboard',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1539',
      name: 'Steal Web Session Cookie',
      tactics: ['credential-access'],
      sub: [],
    },
    {
      id: 'T1542',
      name: 'Pre-OS Boot',
      tactics: ['stealth', 'persistence'],
      sub: [
        {
          id: 'T1542.001',
          name: 'System Firmware',
        },
        {
          id: 'T1542.002',
          name: 'Component Firmware',
        },
        {
          id: 'T1542.003',
          name: 'Bootkit',
        },
        {
          id: 'T1542.004',
          name: 'ROMMONkit',
        },
        {
          id: 'T1542.005',
          name: 'TFTP Boot',
        },
      ],
    },
    {
      id: 'T1543',
      name: 'Create or Modify System Process',
      tactics: ['persistence', 'privilege-escalation'],
      sub: [
        {
          id: 'T1543.001',
          name: 'Launch Agent',
        },
        {
          id: 'T1543.002',
          name: 'Systemd Service',
        },
        {
          id: 'T1543.003',
          name: 'Windows Service',
        },
        {
          id: 'T1543.004',
          name: 'Launch Daemon',
        },
        {
          id: 'T1543.005',
          name: 'Container Service',
        },
      ],
    },
    {
      id: 'T1546',
      name: 'Event Triggered Execution',
      tactics: ['privilege-escalation', 'persistence'],
      sub: [
        {
          id: 'T1546.001',
          name: 'Change Default File Association',
        },
        {
          id: 'T1546.002',
          name: 'Screensaver',
        },
        {
          id: 'T1546.003',
          name: 'Windows Management Instrumentation Event Subscription',
        },
        {
          id: 'T1546.004',
          name: 'Unix Shell Configuration Modification',
        },
        {
          id: 'T1546.005',
          name: 'Trap',
        },
        {
          id: 'T1546.006',
          name: 'LC_LOAD_DYLIB Addition',
        },
        {
          id: 'T1546.007',
          name: 'Netsh Helper DLL',
        },
        {
          id: 'T1546.008',
          name: 'Accessibility Features',
        },
        {
          id: 'T1546.009',
          name: 'AppCert DLLs',
        },
        {
          id: 'T1546.010',
          name: 'AppInit DLLs',
        },
        {
          id: 'T1546.011',
          name: 'Application Shimming',
        },
        {
          id: 'T1546.012',
          name: 'Image File Execution Options Injection',
        },
        {
          id: 'T1546.013',
          name: 'PowerShell Profile',
        },
        {
          id: 'T1546.014',
          name: 'Emond',
        },
        {
          id: 'T1546.015',
          name: 'Component Object Model Hijacking',
        },
        {
          id: 'T1546.016',
          name: 'Installer Packages',
        },
        {
          id: 'T1546.017',
          name: 'Udev Rules',
        },
        {
          id: 'T1546.018',
          name: 'Python Startup Hooks',
        },
      ],
    },
    {
      id: 'T1547',
      name: 'Boot or Logon Autostart Execution',
      tactics: ['persistence', 'privilege-escalation'],
      sub: [
        {
          id: 'T1547.001',
          name: 'Registry Run Keys / Startup Folder',
        },
        {
          id: 'T1547.002',
          name: 'Authentication Package',
        },
        {
          id: 'T1547.003',
          name: 'Time Providers',
        },
        {
          id: 'T1547.004',
          name: 'Winlogon Helper DLL',
        },
        {
          id: 'T1547.005',
          name: 'Security Support Provider',
        },
        {
          id: 'T1547.006',
          name: 'Kernel Modules and Extensions',
        },
        {
          id: 'T1547.007',
          name: 'Re-opened Applications',
        },
        {
          id: 'T1547.008',
          name: 'LSASS Driver',
        },
        {
          id: 'T1547.009',
          name: 'Shortcut Modification',
        },
        {
          id: 'T1547.010',
          name: 'Port Monitors',
        },
        {
          id: 'T1547.012',
          name: 'Print Processors',
        },
        {
          id: 'T1547.013',
          name: 'XDG Autostart Entries',
        },
        {
          id: 'T1547.014',
          name: 'Active Setup',
        },
        {
          id: 'T1547.015',
          name: 'Login Items',
        },
      ],
    },
    {
      id: 'T1548',
      name: 'Abuse Elevation Control Mechanism',
      tactics: ['privilege-escalation'],
      sub: [
        {
          id: 'T1548.001',
          name: 'Setuid and Setgid',
        },
        {
          id: 'T1548.002',
          name: 'Bypass User Account Control',
        },
        {
          id: 'T1548.003',
          name: 'Sudo and Sudo Caching',
        },
        {
          id: 'T1548.004',
          name: 'Elevated Execution with Prompt',
        },
        {
          id: 'T1548.005',
          name: 'Temporary Elevated Cloud Access',
        },
        {
          id: 'T1548.006',
          name: 'TCC Manipulation',
        },
      ],
    },
    {
      id: 'T1550',
      name: 'Use Alternate Authentication Material',
      tactics: ['lateral-movement'],
      sub: [
        {
          id: 'T1550.001',
          name: 'Application Access Token',
        },
        {
          id: 'T1550.002',
          name: 'Pass the Hash',
        },
        {
          id: 'T1550.003',
          name: 'Pass the Ticket',
        },
        {
          id: 'T1550.004',
          name: 'Web Session Cookie',
        },
      ],
    },
    {
      id: 'T1552',
      name: 'Unsecured Credentials',
      tactics: ['credential-access'],
      sub: [
        {
          id: 'T1552.001',
          name: 'Credentials In Files',
        },
        {
          id: 'T1552.002',
          name: 'Credentials in Registry',
        },
        {
          id: 'T1552.003',
          name: 'Shell History',
        },
        {
          id: 'T1552.004',
          name: 'Private Keys',
        },
        {
          id: 'T1552.005',
          name: 'Cloud Instance Metadata API',
        },
        {
          id: 'T1552.006',
          name: 'Group Policy Preferences',
        },
        {
          id: 'T1552.007',
          name: 'Container API',
        },
        {
          id: 'T1552.008',
          name: 'Chat Messages',
        },
      ],
    },
    {
      id: 'T1553',
      name: 'Subvert Trust Controls',
      tactics: ['defense-impairment'],
      sub: [
        {
          id: 'T1553.001',
          name: 'Gatekeeper Bypass',
        },
        {
          id: 'T1553.002',
          name: 'Code Signing',
        },
        {
          id: 'T1553.003',
          name: 'SIP and Trust Provider Hijacking',
        },
        {
          id: 'T1553.004',
          name: 'Install Root Certificate',
        },
        {
          id: 'T1553.005',
          name: 'Mark-of-the-Web Bypass',
        },
        {
          id: 'T1553.006',
          name: 'Code Signing Policy Modification',
        },
      ],
    },
    {
      id: 'T1554',
      name: 'Compromise Host Software Binary',
      tactics: ['persistence'],
      sub: [],
    },
    {
      id: 'T1555',
      name: 'Credentials from Password Stores',
      tactics: ['credential-access'],
      sub: [
        {
          id: 'T1555.001',
          name: 'Keychain',
        },
        {
          id: 'T1555.002',
          name: 'Securityd Memory',
        },
        {
          id: 'T1555.003',
          name: 'Credentials from Web Browsers',
        },
        {
          id: 'T1555.004',
          name: 'Windows Credential Manager',
        },
        {
          id: 'T1555.005',
          name: 'Password Managers',
        },
        {
          id: 'T1555.006',
          name: 'Cloud Secrets Management Stores',
        },
      ],
    },
    {
      id: 'T1556',
      name: 'Modify Authentication Process',
      tactics: ['defense-impairment', 'persistence', 'credential-access'],
      sub: [
        {
          id: 'T1556.001',
          name: 'Domain Controller Authentication',
        },
        {
          id: 'T1556.002',
          name: 'Password Filter DLL',
        },
        {
          id: 'T1556.003',
          name: 'Pluggable Authentication Modules',
        },
        {
          id: 'T1556.004',
          name: 'Network Device Authentication',
        },
        {
          id: 'T1556.005',
          name: 'Reversible Encryption',
        },
        {
          id: 'T1556.006',
          name: 'Multi-Factor Authentication',
        },
        {
          id: 'T1556.007',
          name: 'Hybrid Identity',
        },
        {
          id: 'T1556.008',
          name: 'Network Provider DLL',
        },
        {
          id: 'T1556.009',
          name: 'Conditional Access Policies',
        },
      ],
    },
    {
      id: 'T1557',
      name: 'Adversary-in-the-Middle',
      tactics: ['credential-access', 'collection'],
      sub: [
        {
          id: 'T1557.001',
          name: 'Name Resolution Poisoning and SMB Relay',
        },
        {
          id: 'T1557.002',
          name: 'ARP Cache Poisoning',
        },
        {
          id: 'T1557.003',
          name: 'DHCP Spoofing',
        },
        {
          id: 'T1557.004',
          name: 'Evil Twin',
        },
      ],
    },
    {
      id: 'T1558',
      name: 'Steal or Forge Kerberos Tickets',
      tactics: ['credential-access'],
      sub: [
        {
          id: 'T1558.001',
          name: 'Golden Ticket',
        },
        {
          id: 'T1558.002',
          name: 'Silver Ticket',
        },
        {
          id: 'T1558.003',
          name: 'Kerberoasting',
        },
        {
          id: 'T1558.004',
          name: 'AS-REP Roasting',
        },
        {
          id: 'T1558.005',
          name: 'Ccache Files',
        },
      ],
    },
    {
      id: 'T1559',
      name: 'Inter-Process Communication',
      tactics: ['execution'],
      sub: [
        {
          id: 'T1559.001',
          name: 'Component Object Model',
        },
        {
          id: 'T1559.002',
          name: 'Dynamic Data Exchange',
        },
        {
          id: 'T1559.003',
          name: 'XPC Services',
        },
      ],
    },
    {
      id: 'T1560',
      name: 'Archive Collected Data',
      tactics: ['collection'],
      sub: [
        {
          id: 'T1560.001',
          name: 'Archive via Utility',
        },
        {
          id: 'T1560.002',
          name: 'Archive via Library',
        },
        {
          id: 'T1560.003',
          name: 'Archive via Custom Method',
        },
      ],
    },
    {
      id: 'T1561',
      name: 'Disk Wipe',
      tactics: ['impact'],
      sub: [
        {
          id: 'T1561.001',
          name: 'Disk Content Wipe',
        },
        {
          id: 'T1561.002',
          name: 'Disk Structure Wipe',
        },
      ],
    },
    {
      id: 'T1563',
      name: 'Remote Service Session Hijacking',
      tactics: ['lateral-movement'],
      sub: [
        {
          id: 'T1563.001',
          name: 'SSH Hijacking',
        },
        {
          id: 'T1563.002',
          name: 'RDP Hijacking',
        },
      ],
    },
    {
      id: 'T1564',
      name: 'Hide Artifacts',
      tactics: ['stealth'],
      sub: [
        {
          id: 'T1564.001',
          name: 'Hidden Files and Directories',
        },
        {
          id: 'T1564.002',
          name: 'Hidden Users',
        },
        {
          id: 'T1564.003',
          name: 'Hidden Window',
        },
        {
          id: 'T1564.004',
          name: 'NTFS File Attributes',
        },
        {
          id: 'T1564.005',
          name: 'Hidden File System',
        },
        {
          id: 'T1564.006',
          name: 'Run Virtual Instance',
        },
        {
          id: 'T1564.007',
          name: 'VBA Stomping',
        },
        {
          id: 'T1564.008',
          name: 'Email Hiding Rules',
        },
        {
          id: 'T1564.009',
          name: 'Resource Forking',
        },
        {
          id: 'T1564.010',
          name: 'Process Argument Spoofing',
        },
        {
          id: 'T1564.011',
          name: 'Ignore Process Interrupts',
        },
        {
          id: 'T1564.012',
          name: 'File/Path Exclusions',
        },
        {
          id: 'T1564.013',
          name: 'Bind Mounts',
        },
        {
          id: 'T1564.014',
          name: 'Extended Attributes',
        },
      ],
    },
    {
      id: 'T1565',
      name: 'Data Manipulation',
      tactics: ['impact'],
      sub: [
        {
          id: 'T1565.001',
          name: 'Stored Data Manipulation',
        },
        {
          id: 'T1565.002',
          name: 'Transmitted Data Manipulation',
        },
        {
          id: 'T1565.003',
          name: 'Runtime Data Manipulation',
        },
      ],
    },
    {
      id: 'T1566',
      name: 'Phishing',
      tactics: ['initial-access'],
      sub: [
        {
          id: 'T1566.001',
          name: 'Spearphishing Attachment',
        },
        {
          id: 'T1566.002',
          name: 'Spearphishing Link',
        },
        {
          id: 'T1566.003',
          name: 'Spearphishing via Service',
        },
        {
          id: 'T1566.004',
          name: 'Spearphishing Voice',
        },
      ],
    },
    {
      id: 'T1567',
      name: 'Exfiltration Over Web Service',
      tactics: ['exfiltration'],
      sub: [
        {
          id: 'T1567.001',
          name: 'Exfiltration to Code Repository',
        },
        {
          id: 'T1567.002',
          name: 'Exfiltration to Cloud Storage',
        },
        {
          id: 'T1567.003',
          name: 'Exfiltration to Text Storage Sites',
        },
        {
          id: 'T1567.004',
          name: 'Exfiltration Over Webhook',
        },
      ],
    },
    {
      id: 'T1568',
      name: 'Dynamic Resolution',
      tactics: ['command-and-control'],
      sub: [
        {
          id: 'T1568.001',
          name: 'Fast Flux DNS',
        },
        {
          id: 'T1568.002',
          name: 'Domain Generation Algorithms',
        },
        {
          id: 'T1568.003',
          name: 'DNS Calculation',
        },
      ],
    },
    {
      id: 'T1569',
      name: 'System Services',
      tactics: ['execution'],
      sub: [
        {
          id: 'T1569.001',
          name: 'Launchctl',
        },
        {
          id: 'T1569.002',
          name: 'Service Execution',
        },
        {
          id: 'T1569.003',
          name: 'Systemctl',
        },
      ],
    },
    {
      id: 'T1570',
      name: 'Lateral Tool Transfer',
      tactics: ['lateral-movement'],
      sub: [],
    },
    {
      id: 'T1571',
      name: 'Non-Standard Port',
      tactics: ['command-and-control'],
      sub: [],
    },
    {
      id: 'T1572',
      name: 'Protocol Tunneling',
      tactics: ['command-and-control'],
      sub: [],
    },
    {
      id: 'T1573',
      name: 'Encrypted Channel',
      tactics: ['command-and-control'],
      sub: [
        {
          id: 'T1573.001',
          name: 'Symmetric Cryptography',
        },
        {
          id: 'T1573.002',
          name: 'Asymmetric Cryptography',
        },
      ],
    },
    {
      id: 'T1574',
      name: 'Hijack Execution Flow',
      tactics: ['stealth', 'execution'],
      sub: [
        {
          id: 'T1574.001',
          name: 'DLL',
        },
        {
          id: 'T1574.004',
          name: 'Dylib Hijacking',
        },
        {
          id: 'T1574.005',
          name: 'Executable Installer File Permissions Weakness',
        },
        {
          id: 'T1574.006',
          name: 'Dynamic Linker Hijacking',
        },
        {
          id: 'T1574.007',
          name: 'Path Interception by PATH Environment Variable',
        },
        {
          id: 'T1574.008',
          name: 'Path Interception by Search Order Hijacking',
        },
        {
          id: 'T1574.009',
          name: 'Path Interception by Unquoted Path',
        },
        {
          id: 'T1574.010',
          name: 'Services File Permissions Weakness',
        },
        {
          id: 'T1574.011',
          name: 'Services Registry Permissions Weakness',
        },
        {
          id: 'T1574.012',
          name: 'COR_PROFILER',
        },
        {
          id: 'T1574.013',
          name: 'KernelCallbackTable',
        },
        {
          id: 'T1574.014',
          name: 'AppDomainManager',
        },
      ],
    },
    {
      id: 'T1578',
      name: 'Modify Cloud Compute Infrastructure',
      tactics: ['defense-impairment'],
      sub: [
        {
          id: 'T1578.001',
          name: 'Create Snapshot',
        },
        {
          id: 'T1578.002',
          name: 'Create Cloud Instance',
        },
        {
          id: 'T1578.003',
          name: 'Delete Cloud Instance',
        },
        {
          id: 'T1578.004',
          name: 'Revert Cloud Instance',
        },
        {
          id: 'T1578.005',
          name: 'Modify Cloud Compute Configurations',
        },
      ],
    },
    {
      id: 'T1580',
      name: 'Cloud Infrastructure Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1583',
      name: 'Acquire Infrastructure',
      tactics: ['resource-development'],
      sub: [
        {
          id: 'T1583.001',
          name: 'Domains',
        },
        {
          id: 'T1583.002',
          name: 'DNS Server',
        },
        {
          id: 'T1583.003',
          name: 'Virtual Private Server',
        },
        {
          id: 'T1583.004',
          name: 'Server',
        },
        {
          id: 'T1583.005',
          name: 'Botnet',
        },
        {
          id: 'T1583.006',
          name: 'Web Services',
        },
        {
          id: 'T1583.007',
          name: 'Serverless',
        },
        {
          id: 'T1583.008',
          name: 'Malvertising',
        },
      ],
    },
    {
      id: 'T1584',
      name: 'Compromise Infrastructure',
      tactics: ['resource-development'],
      sub: [
        {
          id: 'T1584.001',
          name: 'Domains',
        },
        {
          id: 'T1584.002',
          name: 'DNS Server',
        },
        {
          id: 'T1584.003',
          name: 'Virtual Private Server',
        },
        {
          id: 'T1584.004',
          name: 'Server',
        },
        {
          id: 'T1584.005',
          name: 'Botnet',
        },
        {
          id: 'T1584.006',
          name: 'Web Services',
        },
        {
          id: 'T1584.007',
          name: 'Serverless',
        },
        {
          id: 'T1584.008',
          name: 'Network Devices',
        },
      ],
    },
    {
      id: 'T1585',
      name: 'Establish Accounts',
      tactics: ['resource-development'],
      sub: [
        {
          id: 'T1585.001',
          name: 'Social Media Accounts',
        },
        {
          id: 'T1585.002',
          name: 'Email Accounts',
        },
        {
          id: 'T1585.003',
          name: 'Cloud Accounts',
        },
      ],
    },
    {
      id: 'T1586',
      name: 'Compromise Accounts',
      tactics: ['resource-development'],
      sub: [
        {
          id: 'T1586.001',
          name: 'Social Media Accounts',
        },
        {
          id: 'T1586.002',
          name: 'Email Accounts',
        },
        {
          id: 'T1586.003',
          name: 'Cloud Accounts',
        },
      ],
    },
    {
      id: 'T1587',
      name: 'Develop Capabilities',
      tactics: ['resource-development'],
      sub: [
        {
          id: 'T1587.001',
          name: 'Malware',
        },
        {
          id: 'T1587.002',
          name: 'Code Signing Certificates',
        },
        {
          id: 'T1587.003',
          name: 'Digital Certificates',
        },
        {
          id: 'T1587.004',
          name: 'Exploits',
        },
      ],
    },
    {
      id: 'T1588',
      name: 'Obtain Capabilities',
      tactics: ['resource-development'],
      sub: [
        {
          id: 'T1588.001',
          name: 'Malware',
        },
        {
          id: 'T1588.002',
          name: 'Tool',
        },
        {
          id: 'T1588.003',
          name: 'Code Signing Certificates',
        },
        {
          id: 'T1588.004',
          name: 'Digital Certificates',
        },
        {
          id: 'T1588.005',
          name: 'Exploits',
        },
        {
          id: 'T1588.006',
          name: 'Vulnerabilities',
        },
        {
          id: 'T1588.007',
          name: 'Artificial Intelligence',
        },
      ],
    },
    {
      id: 'T1589',
      name: 'Gather Victim Identity Information',
      tactics: ['reconnaissance'],
      sub: [
        {
          id: 'T1589.001',
          name: 'Credentials',
        },
        {
          id: 'T1589.002',
          name: 'Email Addresses',
        },
        {
          id: 'T1589.003',
          name: 'Employee Names',
        },
      ],
    },
    {
      id: 'T1590',
      name: 'Gather Victim Network Information',
      tactics: ['reconnaissance'],
      sub: [
        {
          id: 'T1590.001',
          name: 'Domain Properties',
        },
        {
          id: 'T1590.002',
          name: 'DNS',
        },
        {
          id: 'T1590.003',
          name: 'Network Trust Dependencies',
        },
        {
          id: 'T1590.004',
          name: 'Network Topology',
        },
        {
          id: 'T1590.005',
          name: 'IP Addresses',
        },
        {
          id: 'T1590.006',
          name: 'Network Security Appliances',
        },
      ],
    },
    {
      id: 'T1591',
      name: 'Gather Victim Org Information',
      tactics: ['reconnaissance'],
      sub: [
        {
          id: 'T1591.001',
          name: 'Determine Physical Locations',
        },
        {
          id: 'T1591.002',
          name: 'Business Relationships',
        },
        {
          id: 'T1591.003',
          name: 'Identify Business Tempo',
        },
        {
          id: 'T1591.004',
          name: 'Identify Roles',
        },
      ],
    },
    {
      id: 'T1592',
      name: 'Gather Victim Host Information',
      tactics: ['reconnaissance'],
      sub: [
        {
          id: 'T1592.001',
          name: 'Hardware',
        },
        {
          id: 'T1592.002',
          name: 'Software',
        },
        {
          id: 'T1592.003',
          name: 'Firmware',
        },
        {
          id: 'T1592.004',
          name: 'Client Configurations',
        },
      ],
    },
    {
      id: 'T1593',
      name: 'Search Open Websites/Domains',
      tactics: ['reconnaissance'],
      sub: [
        {
          id: 'T1593.001',
          name: 'Social Media',
        },
        {
          id: 'T1593.002',
          name: 'Search Engines',
        },
        {
          id: 'T1593.003',
          name: 'Code Repositories',
        },
      ],
    },
    {
      id: 'T1594',
      name: 'Search Victim-Owned Websites',
      tactics: ['reconnaissance'],
      sub: [],
    },
    {
      id: 'T1595',
      name: 'Active Scanning',
      tactics: ['reconnaissance'],
      sub: [
        {
          id: 'T1595.001',
          name: 'Scanning IP Blocks',
        },
        {
          id: 'T1595.002',
          name: 'Vulnerability Scanning',
        },
        {
          id: 'T1595.003',
          name: 'Wordlist Scanning',
        },
      ],
    },
    {
      id: 'T1596',
      name: 'Search Open Technical Databases',
      tactics: ['reconnaissance'],
      sub: [
        {
          id: 'T1596.001',
          name: 'DNS/Passive DNS',
        },
        {
          id: 'T1596.002',
          name: 'WHOIS',
        },
        {
          id: 'T1596.003',
          name: 'Digital Certificates',
        },
        {
          id: 'T1596.004',
          name: 'CDNs',
        },
        {
          id: 'T1596.005',
          name: 'Scan Databases',
        },
      ],
    },
    {
      id: 'T1597',
      name: 'Search Closed Sources',
      tactics: ['reconnaissance'],
      sub: [
        {
          id: 'T1597.001',
          name: 'Threat Intel Vendors',
        },
        {
          id: 'T1597.002',
          name: 'Purchase Technical Data',
        },
      ],
    },
    {
      id: 'T1598',
      name: 'Phishing for Information',
      tactics: ['reconnaissance'],
      sub: [
        {
          id: 'T1598.001',
          name: 'Spearphishing Service',
        },
        {
          id: 'T1598.002',
          name: 'Spearphishing Attachment',
        },
        {
          id: 'T1598.003',
          name: 'Spearphishing Link',
        },
        {
          id: 'T1598.004',
          name: 'Spearphishing Voice',
        },
      ],
    },
    {
      id: 'T1599',
      name: 'Network Boundary Bridging',
      tactics: ['defense-impairment'],
      sub: [
        {
          id: 'T1599.001',
          name: 'Network Address Translation Traversal',
        },
      ],
    },
    {
      id: 'T1600',
      name: 'Weaken Encryption',
      tactics: ['defense-impairment'],
      sub: [
        {
          id: 'T1600.001',
          name: 'Reduce Key Space',
        },
        {
          id: 'T1600.002',
          name: 'Disable Crypto Hardware',
        },
      ],
    },
    {
      id: 'T1601',
      name: 'Modify System Image',
      tactics: ['defense-impairment'],
      sub: [
        {
          id: 'T1601.001',
          name: 'Patch System Image',
        },
        {
          id: 'T1601.002',
          name: 'Downgrade System Image',
        },
      ],
    },
    {
      id: 'T1602',
      name: 'Data from Configuration Repository',
      tactics: ['collection'],
      sub: [
        {
          id: 'T1602.001',
          name: 'SNMP (MIB Dump)',
        },
        {
          id: 'T1602.002',
          name: 'Network Device Configuration Dump',
        },
      ],
    },
    {
      id: 'T1606',
      name: 'Forge Web Credentials',
      tactics: ['credential-access'],
      sub: [
        {
          id: 'T1606.001',
          name: 'Web Cookies',
        },
        {
          id: 'T1606.002',
          name: 'SAML Tokens',
        },
      ],
    },
    {
      id: 'T1608',
      name: 'Stage Capabilities',
      tactics: ['resource-development'],
      sub: [
        {
          id: 'T1608.001',
          name: 'Upload Malware',
        },
        {
          id: 'T1608.002',
          name: 'Upload Tool',
        },
        {
          id: 'T1608.003',
          name: 'Install Digital Certificate',
        },
        {
          id: 'T1608.004',
          name: 'Drive-by Target',
        },
        {
          id: 'T1608.005',
          name: 'Link Target',
        },
        {
          id: 'T1608.006',
          name: 'SEO Poisoning',
        },
      ],
    },
    {
      id: 'T1609',
      name: 'Container Administration Command',
      tactics: ['execution'],
      sub: [],
    },
    {
      id: 'T1610',
      name: 'Deploy Container',
      tactics: ['execution'],
      sub: [],
    },
    {
      id: 'T1611',
      name: 'Escape to Host',
      tactics: ['privilege-escalation'],
      sub: [],
    },
    {
      id: 'T1612',
      name: 'Build Image on Host',
      tactics: ['stealth'],
      sub: [],
    },
    {
      id: 'T1613',
      name: 'Container and Resource Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1614',
      name: 'System Location Discovery',
      tactics: ['discovery'],
      sub: [
        {
          id: 'T1614.001',
          name: 'System Language Discovery',
        },
      ],
    },
    {
      id: 'T1615',
      name: 'Group Policy Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1619',
      name: 'Cloud Storage Object Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1620',
      name: 'Reflective Code Loading',
      tactics: ['stealth'],
      sub: [],
    },
    {
      id: 'T1621',
      name: 'Multi-Factor Authentication Request Generation',
      tactics: ['credential-access'],
      sub: [],
    },
    {
      id: 'T1622',
      name: 'Debugger Evasion',
      tactics: ['stealth', 'discovery'],
      sub: [],
    },
    {
      id: 'T1647',
      name: 'Plist File Modification',
      tactics: ['defense-impairment'],
      sub: [],
    },
    {
      id: 'T1648',
      name: 'Serverless Execution',
      tactics: ['execution'],
      sub: [],
    },
    {
      id: 'T1649',
      name: 'Steal or Forge Authentication Certificates',
      tactics: ['credential-access'],
      sub: [],
    },
    {
      id: 'T1650',
      name: 'Acquire Access',
      tactics: ['resource-development'],
      sub: [],
    },
    {
      id: 'T1651',
      name: 'Cloud Administration Command',
      tactics: ['execution'],
      sub: [],
    },
    {
      id: 'T1652',
      name: 'Device Driver Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1653',
      name: 'Power Settings',
      tactics: ['persistence'],
      sub: [],
    },
    {
      id: 'T1654',
      name: 'Log Enumeration',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1657',
      name: 'Financial Theft',
      tactics: ['impact'],
      sub: [],
    },
    {
      id: 'T1659',
      name: 'Content Injection',
      tactics: ['initial-access', 'command-and-control'],
      sub: [],
    },
    {
      id: 'T1665',
      name: 'Hide Infrastructure',
      tactics: ['command-and-control'],
      sub: [],
    },
    {
      id: 'T1666',
      name: 'Modify Cloud Resource Hierarchy',
      tactics: ['defense-impairment'],
      sub: [],
    },
    {
      id: 'T1667',
      name: 'Email Bombing',
      tactics: ['impact'],
      sub: [],
    },
    {
      id: 'T1668',
      name: 'Exclusive Control',
      tactics: ['persistence'],
      sub: [],
    },
    {
      id: 'T1669',
      name: 'Wi-Fi Networks',
      tactics: ['initial-access'],
      sub: [],
    },
    {
      id: 'T1671',
      name: 'Cloud Application Integration',
      tactics: ['persistence'],
      sub: [],
    },
    {
      id: 'T1673',
      name: 'Virtual Machine Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1674',
      name: 'Input Injection',
      tactics: ['execution'],
      sub: [],
    },
    {
      id: 'T1675',
      name: 'ESXi Administration Command',
      tactics: ['execution'],
      sub: [],
    },
    {
      id: 'T1677',
      name: 'Poisoned Pipeline Execution',
      tactics: ['execution'],
      sub: [],
    },
    {
      id: 'T1678',
      name: 'Delay Execution',
      tactics: ['stealth'],
      sub: [],
    },
    {
      id: 'T1679',
      name: 'Selective Exclusion',
      tactics: ['stealth'],
      sub: [],
    },
    {
      id: 'T1680',
      name: 'Local Storage Discovery',
      tactics: ['discovery'],
      sub: [],
    },
    {
      id: 'T1681',
      name: 'Search Threat Vendor Data',
      tactics: ['reconnaissance'],
      sub: [],
    },
    {
      id: 'T1682',
      name: 'Query Public AI Services',
      tactics: ['reconnaissance'],
      sub: [],
    },
    {
      id: 'T1683',
      name: 'Generate Content',
      tactics: ['resource-development'],
      sub: [
        {
          id: 'T1683.001',
          name: 'Written Content',
        },
        {
          id: 'T1683.002',
          name: 'Audio-Visual Content',
        },
      ],
    },
    {
      id: 'T1684',
      name: 'Social Engineering',
      tactics: ['stealth'],
      sub: [
        {
          id: 'T1684.001',
          name: 'Impersonation',
        },
        {
          id: 'T1684.002',
          name: 'Email Spoofing',
        },
      ],
    },
    {
      id: 'T1685',
      name: 'Disable or Modify Tools',
      tactics: ['defense-impairment'],
      sub: [
        {
          id: 'T1685.001',
          name: 'Disable or Modify Windows Event Log',
        },
        {
          id: 'T1685.002',
          name: 'Disable or Modify Cloud Log',
        },
        {
          id: 'T1685.003',
          name: 'Modify or Spoof Tool UI',
        },
        {
          id: 'T1685.004',
          name: 'Disable or Modify Linux Audit System Log',
        },
        {
          id: 'T1685.005',
          name: 'Clear Windows Event Logs',
        },
        {
          id: 'T1685.006',
          name: 'Clear Linux or Mac System Logs',
        },
      ],
    },
    {
      id: 'T1686',
      name: 'Disable or Modify System Firewall',
      tactics: ['defense-impairment'],
      sub: [
        {
          id: 'T1686.001',
          name: 'Cloud Firewall',
        },
        {
          id: 'T1686.002',
          name: 'Network Device Firewall',
        },
        {
          id: 'T1686.003',
          name: 'Windows Host Firewall',
        },
      ],
    },
    {
      id: 'T1687',
      name: 'Exploitation for Defense Impairment',
      tactics: ['defense-impairment'],
      sub: [],
    },
    {
      id: 'T1688',
      name: 'Safe Mode Boot',
      tactics: ['defense-impairment'],
      sub: [],
    },
    {
      id: 'T1689',
      name: 'Downgrade Attack',
      tactics: ['defense-impairment'],
      sub: [],
    },
    {
      id: 'T1690',
      name: 'Prevent Command History Logging',
      tactics: ['defense-impairment'],
      sub: [],
    },
  ],
};
